from flask_app.features.fig4pm_features.fig4pm_feature_functions import *
import sys


def get_fig4pm_feature_functions_dict():
    feature_functions = {
        "total_number_of_events": feature_total_number_of_events,
        "total_number_of_event_classes": feature_total_number_of_event_classes,
        "total_number_of_traces": feature_total_number_of_traces,
        "total_number_of_trace_classes": feature_total_number_of_trace_classes,
        "average_trace_length": feature_average_trace_length,
        "minimum_trace_length": feature_minimum_trace_length,
        "maximum_trace_length": feature_maximum_trace_length,
        "average_trace_size": feature_average_trace_size,
        "number_of_distinct_start_events": feature_number_of_distinct_start_events,
        "number_of_distinct_end_events": feature_number_of_distinct_end_events,
        "absolute_number_of_traces_with_self_loop": feature_absolute_number_of_traces_with_self_loop,
        "absoulute_number_of_traces_with_repetition": feature_absoulute_number_of_traces_with_repetition,
        "relative_number_of_distinct_start_events": feature_relative_number_of_distinct_start_events,
        "relative_number_of_distinct_end_events": feature_relative_number_of_distinct_end_events,
        "relative_number_of_traces_with_self_loop": feature_relative_number_of_traces_with_self_loop,
        "relative_number_of_traces_with_repetition": feature_relative_number_of_traces_with_repetition,
        "average_number_of_self_loops_per_trace": feature_average_number_of_self_loops_per_trace,
        "maximum_number_of_self_loops_per_trace": feature_maximum_number_of_self_loops_per_trace,
        "average_size_of_self_loops_per_trace": feature_average_size_of_self_loops_per_trace,
        "maximum_size_of_self_loops_per_trace": feature_maximum_size_of_self_loops_per_trace,
        "number_of_distinct_traces_per_hundred_traces": feature_number_of_distinct_traces_per_hundred_traces,
        "absolute_trace_coverage": feature_absolute_trace_coverage,
        "relative_trace_coverage": feature_relative_trace_coverage,
        "event_density": feature_event_density,
        "traces_heterogeneity_rate": feature_traces_heterogeneity_rate,
        "trace_similarity_rate": feature_trace_similarity_rate,
        "complexity_factor": feature_complexity_factor,
        "simple_trace_diversity": feature_simple_trace_diversity,
        "advanced_trace_diversity": feature_advanced_trace_diversity,
        "trace_entropy": feature_trace_entropy,
        "prefix_entropy": feature_prefix_entropy,
        "all_block_entropy": feature_all_block_entropy,
        "number_of_nodes": feature_number_of_nodes,
        "number_of_arcs": feature_number_of_arcs,
        "coefficient_of_network_connectivity": feature_coefficient_of_network_connectivity,
        "average_node_degree": feature_average_node_degree,
        "maximum_node_degree": feature_maximum_node_degree,
        "density": feature_density,
        "structure": feature_structure,
        "cyclomatic_number": feature_cyclomatic_number,
        "number_of_cut_vertices": feature_number_of_cut_vertices,
        "separability_ratio": feature_separability_ratio,
        "sequentiality_ratio": feature_sequentiality_ratio,
        "affinity": feature_affinity,
        "start_event_frequency_evaluation": feature_start_event_frequency_evaluation,
        "end_event_frequency_evaluation": feature_end_event_frequency_evaluation,
        "event_frequency_evaluation": feature_event_frequency_evaluation,
        "trace_frequency_evaluation": feature_trace_frequency_evaluation,
        "event_dependency_evaluation": feature_event_dependency_evaluation,
        "trace_length_evaluation": feature_trace_length_evaluation,
        "event_profile_average_euclidean_distance": feature_event_profile_average_euclidean_distance,
        "event_profile_average_cosine_similarity": feature_event_profile_average_cosine_similarity,
        "transition_profile_average_euclidean_distance": feature_transition_profile_average_euclidean_distance,
        "average_spatial_proximity": feature_average_spatial_proximity,
        "spatial_proximity_connectedness": feature_spatial_proximity_connectedness,
        "spatial_proximity_abstraction_evaluation": feature_spatial_proximity_abstraction_evaluation,
        "event_dependency_abstraction_evaluation": feature_event_dependency_abstraction_evaluation,
        "triple_abstraction_evaluation": feature_triple_abstraction_evaluation,
        "event_class_triple_abstraction_evaluation": feature_event_class_triple_abstraction_evaluation,
        "number_of_graph_communities": feature_number_of_graph_communities,
        "maximum_cut_vertex_outgoing_degree": feature_maximum_cut_vertex_outgoing_degree,
        "cut_vertex_independent_path": feature_cut_vertex_independent_path,
        "syntactic_node_similarity": feature_syntactic_node_similarity,
        "event_profile_minimum_cosine_similarity": feature_event_profile_minimum_cosine_similarity

    }
    return feature_functions
    # "transition_profile_average_cosine_similarity": feature_transition_profile_average_cosine_similarity,
    #        "transition_profile_minimum_cosine_similarity": feature_transition_profile_minimum_cosine_similarity,
    #        "simple_path_complexity": feature_simple_path_complexity,
    #        "simple_path_minimum_jaccard_similarity": feature_simple_path_minimum_jaccard_similarity,
    #        "number_of_outlying_traces": feature_number_of_outlying_traces,
    #      "relative_number_of_outlying_traces": feature_relative_number_of_outlying_traces,
    #        "graph_diameter": feature_graph_diameter,
    #    "cyclicity": feature_cyclicity,
