#!/usr/bin/env python

import sys
sys.path.append('/home/qc261227/Recommender/RecommenderSystem/backend/flask_app/smac-v2.10.03-master-778')



import logging
import sys
import os
import inspect
cmd_folder = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]))
cmd_folder = os.path.realpath(os.path.join(cmd_folder, ".."))
if cmd_folder not in sys.path:
    sys.path.insert(0,cmd_folder)
    
from autofolio.autofolio import AutoFolio

if __name__ == "__main__":
    
    #logging.basicConfig(level=logging.INFO)
    
    af = AutoFolio()
    af.run_cli()
    
