name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies (Frontend)
        working-directory: frontend/proreco
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend/proreco
        run: |
          npm run build

      - name: Tar the dist
        run: |
          tar -cvf ~/dist.tar ./frontend/proreco/dist

          tar -xvf ~/dist.tar

      - name: Copy file via SSH password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 139.162.188.197
          username: root
          source: "~/dist.tar"
          key: ${{ secrets.MAC_PRIVATEKEY }}
          target: "/var/www/proreco.co"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Restart Nginx
        run: |
          ssh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_IP }} "sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co; sudo systemctl restart nginx"
