name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm build frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.162.188.197
          username: root
          key: ${{ secrets.MAC_PRIVATEKEY }}
          script: |
            cd ~/RecommenderSystem
            git pull
            cd ~/RecommenderSystem/frontend/proreco
            npm install
            npm run build
      - name: start front- and backendservers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.162.188.197
          username: root
          key: ${{ secrets.MAC_PRIVATEKEY }}
          script: |
            sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co;
            sudo systemctl restart nginx
            source /root/miniconda3/bin/activate proreco
            cd ~/RecommenderSystem/backend/flask_app
            nohup gunicorn -c gunicorn_config.py app:app > output.log 2>&1 &
            netstat -tuln | grep 8000
