name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies (Frontend)
        working-directory: frontend/proreco
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend/proreco
        run: |
          npm run build

      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          source: "./dist/*"
          target: /var/www/proreco.c

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Restart Nginx
        run: |
          ssh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_IP }} "sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co;sudo systemctl restart nginx"
