name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote SSH Commands using Key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.162.188.197
          username: root
          key: ${{ secrets.MAC_PRIVATEKEY }}
          script: |
            cd ~/RecommenderSystem/frontend/proreco
            npm run build
            mv ~/RecommenderSystem/frontend/proreco/dist* /var/www/proreco.co/
            sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co
            sudo systemctl restart nginx
            echo 'node -v' >> ~/RecommenderSystem/hi.txt
