name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm build frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.162.188.197
          username: root
          key: ${{ secrets.MAC_PRIVATEKEY }}
          script: |
            sudo find /var/www/proreco.co -mindepth 1 -delete
            cd ~/RecommenderSystem/frontend/proreco
            npm run build
            mv ~/RecommenderSystem/frontend/proreco/dist/* /var/www/proreco.co/

      - name: start front- and backendservers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.162.188.197
          username: root
          key: ${{ secrets.MAC_PRIVATEKEY }}
          script: |
            sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co;
            sudo systemctl restart nginx
            nohup gunicorn -b 0.0.0.0:8000 -w 3 --timeout 120 app:app --env FLASK_ENV=production > /dev/null 2>&1 &
