name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies (Frontend)
        working-directory: frontend/proreco
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend/proreco
        run: |
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Deploy to Linode
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MAC_PRIVATEKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LINODE_IP }} >> ~/.ssh/known_hosts
          scp -r ./frontend/proreco/dist/* ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_IP }}:${{ secrets.LINODE_PATH }}
      - name: Restart Nginx
        run: |
          ssh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_IP }} "sudo chcon -Rt httpd_sys_content_t /var/www/proreco.co;sudo systemctl restart nginx"
